=== Tanaguru/Tanaguru/engine/persistence/src/test/resources/dataSets/test.dtd
<!ELEMENT dataset (
    AUDIT*,
    AUDIT_PARAMETER*,
    AUDIT_TEST*,
    CONTENT*,
    CONTENT_RELATIONSHIP*,
    CRITERION*,
    DECISION_LEVEL*,
    EVIDENCE*,
    EVIDENCE_ELEMENT*,
    LEVEL*,
    NOMENCLATURE*,
    NOMENCLATURE_ELEMENT*,
    PARAMETER*,
    PARAMETER_ELEMENT*,
    PARAMETER_FAMILY*,
    PROCESS_REMARK*,
    PROCESS_RESULT*,
    REFERENCE*,
    RULE*,
    RULE_PACKAGE*,
    SCOPE*,
    STANDARD_MESSAGE*,
    TEST*,
    THEME*,
    WEB_RESOURCE*)>

<!ELEMENT AUDIT EMPTY>
<!ATTLIST AUDIT
    Id_Audit CDATA #REQUIRED
    Comment CDATA #IMPLIED
    Dt_Creation CDATA #IMPLIED
    Status CDATA #IMPLIED
>

<!ELEMENT AUDIT_TEST EMPTY>
<!ATTLIST AUDIT_TEST
    Id_Audit CDATA #REQUIRED
    Id_Test CDATA #REQUIRED
>

<!ELEMENT AUDIT_PARAMETER EMPTY>
<!ATTLIST AUDIT_PARAMETER
    Id_Audit CDATA #REQUIRED
    Id_Parameter CDATA #REQUIRED
>

<!ELEMENT CONTENT EMPTY>
<!ATTLIST CONTENT
    DTYPE CDATA #REQUIRED
    Id_Content CDATA #REQUIRED
    Dt_Loading CDATA #IMPLIED
    Http_Status_Code CDATA #IMPLIED
    Uri CDATA #REQUIRED
    Binary_Content CDATA #IMPLIED
    Adapted_Content CDATA #IMPLIED
    Source CDATA #IMPLIED
    Charset CDATA #IMPLIED
    Doctype CDATA #IMPLIED
    Id_Audit CDATA #IMPLIED
    Id_Page CDATA #IMPLIED
>

<!ELEMENT CONTENT_RELATIONSHIP EMPTY>
<!ATTLIST CONTENT_RELATIONSHIP
    Id_Content_Child CDATA #REQUIRED
    Id_Content_Parent CDATA #REQUIRED
>

<!ELEMENT CRITERION EMPTY>
<!ATTLIST CRITERION
    Id_Criterion CDATA #REQUIRED
    Cd_Criterion CDATA #IMPLIED
    Description CDATA #IMPLIED
    Label CDATA #IMPLIED
    Rank CDATA #IMPLIED
    Url CDATA #IMPLIED
    Reference_Id_Reference CDATA #IMPLIED
    Theme_Id_Theme CDATA #IMPLIED
>

<!ELEMENT DECISION_LEVEL EMPTY>
<!ATTLIST DECISION_LEVEL
    Id_Decision_Level CDATA #REQUIRED
    Cd_Decision_Level CDATA #IMPLIED
    Description CDATA #IMPLIED
    Label CDATA #REQUIRED
>

<!ELEMENT EVIDENCE EMPTY>
<!ATTLIST EVIDENCE
    Id_Evidence CDATA #REQUIRED
    Cd_Evidence CDATA #IMPLIED
    Description CDATA #IMPLIED
    Long_Label CDATA #IMPLIED
>

<!ELEMENT EVIDENCE_ELEMENT EMPTY>
<!ATTLIST EVIDENCE_ELEMENT
    Id_Evidence_Element CDATA #REQUIRED
    Element_Value CDATA #REQUIRED
    EVIDENCE_Id_Evidence CDATA #IMPLIED
    PROCESS_REMARK_Id_Process_Remark CDATA #IMPLIED
>

<!ELEMENT LEVEL EMPTY>
<!ATTLIST LEVEL
    Id_Level CDATA #REQUIRED
    Cd_Level CDATA #IMPLIED
    Description CDATA #IMPLIED
    Label CDATA #IMPLIED
    Rank CDATA #IMPLIED
>

<!ELEMENT PARAMETER EMPTY>
<!ATTLIST PARAMETER
    Id_Parameter CDATA #REQUIRED
    Id_Parameter_Element CDATA #REQUIRED
    Parameter_Value CDATA #REQUIRED
    Is_Default CDATA #IMPLIED
>

<!ELEMENT PARAMETER_ELEMENT EMPTY>
<!ATTLIST PARAMETER_ELEMENT
    Id_Parameter_Element CDATA #REQUIRED
    Cd_Parameter_Element CDATA #REQUIRED
    Id_Parameter_Family CDATA #REQUIRED
    Short_Label CDATA #IMPLIED
    Long_Label CDATA #IMPLIED
>

<!ELEMENT PARAMETER_FAMILY EMPTY>
<!ATTLIST PARAMETER_FAMILY
    Id_Parameter_Family CDATA #REQUIRED
    Cd_Parameter_Family CDATA #REQUIRED
    Description CDATA #IMPLIED
    Short_Label CDATA #IMPLIED
    Long_Label CDATA #IMPLIED
>

<!ELEMENT NOMENCLATURE EMPTY>
<!ATTLIST NOMENCLATURE
    Id_Nomenclature CDATA #REQUIRED
    Cd_Nomenclature CDATA #IMPLIED
    Description CDATA #IMPLIED
    Long_Label CDATA #IMPLIED
    Short_Label CDATA #IMPLIED
    Id_Nomenclature_Parent CDATA #IMPLIED
>

<!ELEMENT NOMENCLATURE_ELEMENT EMPTY>
<!ATTLIST NOMENCLATURE_ELEMENT
    DTYPE CDATA #REQUIRED
    Id_Nomenclature_Element CDATA #REQUIRED
    Label CDATA #REQUIRED
    shortValue CDATA #IMPLIED
    Id_Nomenclature CDATA #IMPLIED
>

<!ELEMENT PROCESS_REMARK EMPTY>
<!ATTLIST PROCESS_REMARK
    DTYPE CDATA #REQUIRED
    Id_Process_Remark CDATA #REQUIRED
    Issue CDATA #IMPLIED
    Message_Code CDATA #IMPLIED
    Selected_Element CDATA #IMPLIED
    Selection_Expression CDATA #IMPLIED
    Character_Position CDATA #IMPLIED
    Line_Number CDATA #IMPLIED
    Target CDATA #IMPLIED
    Id_Process_Result CDATA #IMPLIED
>

<!ELEMENT PROCESS_RESULT EMPTY>
<!ATTLIST PROCESS_RESULT
    DTYPE CDATA #REQUIRED
    Id_Process_Result CDATA #REQUIRED
    Element_Counter CDATA #IMPLIED
    Definite_Value CDATA #IMPLIED
    Indefinite_Value CDATA #IMPLIED
    Id_Audit_Gross_Result CDATA #IMPLIED
    Id_Audit_Net_Result CDATA #IMPLIED
    Id_Process_Result_Parent CDATA #IMPLIED
    Id_Web_Resource CDATA #REQUIRED
    Id_Test CDATA #IMPLIED
>

<!ELEMENT REFERENCE EMPTY>
<!ATTLIST REFERENCE
    Id_Reference CDATA #REQUIRED
    Cd_Reference CDATA #IMPLIED
    Description CDATA #IMPLIED
    Label CDATA #REQUIRED
    Rank CDATA #IMPLIED
    Url CDATA #IMPLIED
>

<!ELEMENT RULE EMPTY>
<!ATTLIST RULE
    Id_Rule CDATA #REQUIRED
    Class_Name CDATA #REQUIRED
    Description CDATA #IMPLIED
    Id_Rule_Package CDATA #IMPLIED
>

<!ELEMENT RULE_PACKAGE EMPTY>
<!ATTLIST RULE_PACKAGE
    Id_Rule_Package CDATA #REQUIRED
    Description CDATA #IMPLIED
    Package_Name CDATA #IMPLIED
>

<!ELEMENT SCOPE EMPTY>
<!ATTLIST SCOPE
    Id_Scope CDATA #REQUIRED
    Code CDATA #IMPLIED
    Description CDATA #IMPLIED
    Label CDATA #REQUIRED
>

<!ELEMENT STANDARD_MESSAGE EMPTY>
<!ATTLIST STANDARD_MESSAGE
    Id_Standard_Message CDATA #REQUIRED
    Cd_Standard_Message CDATA #IMPLIED
    Label CDATA #IMPLIED
    Text CDATA #IMPLIED
>

<!ELEMENT TEST EMPTY>
<!ATTLIST TEST
    Id_Test CDATA #REQUIRED
    Cd_Test CDATA #IMPLIED
    Description CDATA #IMPLIED
    Label CDATA #IMPLIED
    Rank CDATA #IMPLIED
    Weight CDATA #REQUIRED
    Rule_Archive_Name CDATA #IMPLIED
    Rule_Class_Name CDATA #IMPLIED
    Rule_Design_Url CDATA #IMPLIED
    Id_Criterion CDATA #IMPLIED
    Id_Decision_Level CDATA #IMPLIED
    Id_Level CDATA #IMPLIED
    Id_Scope CDATA #IMPLIED
    No_Process CDATA #IMPLIED
>

<!ELEMENT THEME EMPTY>
<!ATTLIST THEME
    Id_Theme CDATA #REQUIRED
    Cd_Theme CDATA #IMPLIED
    Description CDATA #IMPLIED
    Label CDATA #REQUIRED
    Rank CDATA #IMPLIED
>

<!ELEMENT WEB_RESOURCE EMPTY>
<!ATTLIST WEB_RESOURCE
    DTYPE CDATA #REQUIRED
    Id_Web_Resource CDATA #REQUIRED
    Label CDATA #IMPLIED
    Url CDATA #REQUIRED
    Rank CDATA #REQUIRED
    Id_Audit CDATA #IMPLIED
    Id_Web_Resource_Parent CDATA #IMPLIED
>

=== Tanaguru/Tanaguru/engine/persistence/src/test/resources/dataSets/contentFlatXmlDataSet.xml
<!DOCTYPE dataset SYSTEM "src/test/resources/dataSets/test.dtd">
<dataset>
    
    <AUDIT Id_Audit="1" Dt_Creation="2010-10-26 13:50:29" Status="COMPLETED"/>
    <AUDIT Id_Audit="2" Dt_Creation="2010-10-26 14:50:29" Status="COMPLETED"/>
    <AUDIT Id_Audit="3" Dt_Creation="2010-10-26 14:50:29" Status="COMPLETED"/>

    <WEB_RESOURCE DTYPE="SiteImpl" Id_Web_Resource="1" Label="NULL" Url="http://www.mock-url1.org/" Id_Audit="1" Id_Web_Resource_Parent="[NULL]" Rank="0"/>
    <WEB_RESOURCE DTYPE="PageImpl" Id_Web_Resource="2" Label="NULL" Url="http://www.mock-url2.org/" Id_Audit="2" Id_Web_Resource_Parent="[NULL]" Rank="1"/>
    <WEB_RESOURCE DTYPE="PageImpl" Id_Web_Resource="5" Label="NULL" Url="http://www.mock-url2.org/" Id_Web_Resource_Parent="1" Rank="1"/>
    <WEB_RESOURCE DTYPE="PageImpl" Id_Web_Resource="6" Label="NULL" Url="http://www.mock-url4.org/" Id_Web_Resource_Parent="1" Rank="2"/>
    <WEB_RESOURCE DTYPE="PageImpl" Id_Web_Resource="7" Label="NULL" Url="http://www.mock-url5.org/" Id_Web_Resource_Parent="1" Rank="3"/>
    <WEB_RESOURCE DTYPE="SiteImpl" Id_Web_Resource="8" Label="NULL" Url="http://www.mock-url1.org/" Id_Audit="3" Id_Web_Resource_Parent="[NULL]" Rank="0"/>
    <WEB_RESOURCE DTYPE="PageImpl" Id_Web_Resource="9" Label="NULL" Url="http://www.mock-url2.org/" Id_Web_Resource_Parent="8" Rank="1"/>
    <WEB_RESOURCE DTYPE="PageImpl" Id_Web_Resource="10" Label="NULL" Url="http://www.mock-url4.org/" Id_Web_Resource_Parent="8" Rank="2"/>

    <CONTENT DTYPE="SSPImpl"                Id_Content="1" Uri="http://www.mock-url.org/1.html" Id_Page="5" Http_Status_Code="-1" Id_Audit="1"/>
    <CONTENT DTYPE="SSPImpl"                Id_Content="2" Uri="http://www.mock-url.org/2.html" Id_Page="6" Http_Status_Code="-1" Id_Audit="1"/>
    <CONTENT DTYPE="StylesheetContentImpl"  Id_Content="3" Uri="http://www.mock-url.org/css.css" Http_Status_Code="-1" Id_Audit="1"/>
    <CONTENT DTYPE="ImageContentImpl"       Id_Content="4" Uri="http://www.mock-url.org/image.jpg" Http_Status_Code="-1" Id_Audit="1"/>
    <CONTENT DTYPE="RelatedContentImpl"     Id_Content="5" Uri="http://www.mock-url.org/unknown" Http_Status_Code="-1" Id_Audit="1"/>
    <CONTENT DTYPE="RelatedContentImpl"     Id_Content="6" Uri="http://www.mock-url.org/unknown" Http_Status_Code="-1" Id_Audit="1"/>
    <CONTENT DTYPE="SSPImpl"                Id_Content="7" Uri="http://www.mock-url.org/2.html" Id_Page="2" Http_Status_Code="-1" Id_Audit="2"/>
    <CONTENT DTYPE="StylesheetContentImpl"  Id_Content="8" Uri="http://www.mock-url.org/css.css" Http_Status_Code="-1" Id_Audit="2"/>
    <CONTENT DTYPE="SSPImpl"                Id_Content="9" Uri="http://www.mock-url.org/1.html" Source="blabla" Adapted_Content="blabla" Id_Page="9" Http_Status_Code="404" Id_Audit="3"/>
    <CONTENT DTYPE="SSPImpl"                Id_Content="10" Uri="http://www.mock-url.org/2.html" Id_Page="10" Http_Status_Code="200" Id_Audit="3"/>
    <CONTENT DTYPE="StylesheetContentImpl"  Id_Content="11" Uri="http://www.mock-url.org/css.css" Http_Status_Code="200" Id_Audit="3"/>
    <CONTENT DTYPE="ImageContentImpl"       Id_Content="12" Uri="http://www.mock-url.org/image.jpg" Http_Status_Code="200" Id_Audit="3"/>
    <CONTENT DTYPE="RelatedContentImpl"     Id_Content="13" Uri="http://www.mock-url.org/unknown" Http_Status_Code="200" Id_Audit="3"/>
    <CONTENT DTYPE="RelatedContentImpl"     Id_Content="14" Uri="http://www.mock-url.org/unknown" Http_Status_Code="200" Id_Audit="3"/>

    <CONTENT_RELATIONSHIP Id_Content_Parent="1" Id_Content_Child="3"/>
    <CONTENT_RELATIONSHIP Id_Content_Parent="1" Id_Content_Child="4"/>
    <CONTENT_RELATIONSHIP Id_Content_Parent="1" Id_Content_Child="5"/>
    <CONTENT_RELATIONSHIP Id_Content_Parent="2" Id_Content_Child="3"/>
    <CONTENT_RELATIONSHIP Id_Content_Parent="2" Id_Content_Child="4"/>
    <CONTENT_RELATIONSHIP Id_Content_Parent="7" Id_Content_Child="8"/>
    <CONTENT_RELATIONSHIP Id_Content_Parent="9" Id_Content_Child="11"/>
    <CONTENT_RELATIONSHIP Id_Content_Parent="9" Id_Content_Child="12"/>
    <CONTENT_RELATIONSHIP Id_Content_Parent="9" Id_Content_Child="13"/>
    <CONTENT_RELATIONSHIP Id_Content_Parent="10" Id_Content_Child="11"/>
    <CONTENT_RELATIONSHIP Id_Content_Parent="10" Id_Content_Child="12"/>

</dataset>

=== Tanaguru/Tanaguru/engine/persistence/src/test/resources/dataSets/parameterizationDataSet.xml
<!DOCTYPE dataset SYSTEM "src/test/resources/dataSets/test.dtd">
<dataset>
    
    <AUDIT Id_Audit="1" Dt_Creation="2010-10-26 13:50:29" Status="COMPLETED"/>
    <AUDIT Id_Audit="2" Dt_Creation="2010-10-26 14:50:29" Status="COMPLETED"/>
    <AUDIT Id_Audit="3" Dt_Creation="2010-10-26 15:50:29" Status="COMPLETED"/>
    <AUDIT Id_Audit="4" Dt_Creation="2010-10-26 16:50:29" Status="COMPLETED"/>
    <AUDIT Id_Audit="5" Dt_Creation="2010-10-26 17:50:29" Status="COMPLETED"/>

    <PARAMETER_FAMILY Id_Parameter_Family="1" Cd_Parameter_Family="PARAM_FAM_1"/>
    <PARAMETER_FAMILY Id_Parameter_Family="2" Cd_Parameter_Family="PARAM_FAM_2"/>

    <PARAMETER_ELEMENT Id_Parameter_Element="1" Cd_Parameter_Element="PARAM_EL_1" Id_Parameter_Family="1"/>
    <PARAMETER_ELEMENT Id_Parameter_Element="2" Cd_Parameter_Element="PARAM_EL_2" Id_Parameter_Family="1"/>

    <PARAMETER Id_Parameter="1" Id_Parameter_Element="1" Parameter_Value="Value1" Is_Default="1"/>
    <PARAMETER Id_Parameter="2" Id_Parameter_Element="1" Parameter_Value="Value2" Is_Default="0"/>
    <PARAMETER Id_Parameter="3" Id_Parameter_Element="1" Parameter_Value="Value3" Is_Default="0"/>
    <PARAMETER Id_Parameter="4" Id_Parameter_Element="1" Parameter_Value="Value4" Is_Default="0"/>
    <PARAMETER Id_Parameter="5" Id_Parameter_Element="2" Parameter_Value="Value5" Is_Default="1"/>
    <PARAMETER Id_Parameter="6" Id_Parameter_Element="2" Parameter_Value="Value6" Is_Default="1"/>
    <PARAMETER Id_Parameter="7" Id_Parameter_Element="2" Parameter_Value="Value7" Is_Default="0"/>
    <PARAMETER Id_Parameter="8" Id_Parameter_Element="2" Parameter_Value="Value8" Is_Default="0"/>

    <AUDIT_PARAMETER Id_Audit="1" Id_Parameter="1"/>
    <AUDIT_PARAMETER Id_Audit="1" Id_Parameter="5"/>

    <AUDIT_PARAMETER Id_Audit="2" Id_Parameter="2"/>
    <AUDIT_PARAMETER Id_Audit="2" Id_Parameter="6"/>

    <AUDIT_PARAMETER Id_Audit="3" Id_Parameter="3"/>
    <AUDIT_PARAMETER Id_Audit="3" Id_Parameter="7"/>

    <AUDIT_PARAMETER Id_Audit="4" Id_Parameter="4"/>
    <AUDIT_PARAMETER Id_Audit="4" Id_Parameter="8"/>

</dataset>

=== Tanaguru/Tanaguru/engine/persistence/src/test/resources/dataSets/webresourceFlatXmlDataSet.xml
<!DOCTYPE dataset SYSTEM "src/test/resources/dataSets/test.dtd">
<dataset>
    
    <AUDIT Id_Audit="1" Dt_Creation="2010-10-26 13:50:29" Status="COMPLETED"/>
    <AUDIT Id_Audit="2" Dt_Creation="2010-10-26 14:50:29" Status="COMPLETED"/>
    <AUDIT Id_Audit="3" Dt_Creation="2010-10-26 15:50:29" Status="COMPLETED"/>
    <AUDIT Id_Audit="4" Dt_Creation="2010-10-26 15:50:29" Status="COMPLETED"/>

    <WEB_RESOURCE DTYPE="SiteImpl" Id_Web_Resource="1" Label="NULL" Url="http://www.mock-url1.org/" Id_Audit="1" Id_Web_Resource_Parent="[NULL]" Rank="0"/>
    <WEB_RESOURCE DTYPE="PageImpl" Id_Web_Resource="5" Label="NULL" Url="http://www.mock-url1.org/" Id_Audit="2" Id_Web_Resource_Parent="[NULL]" Rank="1"/>
    <WEB_RESOURCE DTYPE="PageImpl" Id_Web_Resource="6" Label="NULL" Url="http://www.mock-url1.org/" Id_Audit="3" Id_Web_Resource_Parent="[NULL]" Rank="1"/>
    <WEB_RESOURCE DTYPE="PageImpl" Id_Web_Resource="7" Label="NULL" Url="http://www.mock-url1.org/" Id_Audit="4" Id_Web_Resource_Parent="[NULL]" Rank="1"/>
    <WEB_RESOURCE DTYPE="PageImpl" Id_Web_Resource="2" Label="NULL" Url="http://www.mock-url2.org/" Id_Web_Resource_Parent="1" Rank="1"/>
    <WEB_RESOURCE DTYPE="PageImpl" Id_Web_Resource="3" Label="NULL" Url="http://www.mock-url3.org/" Id_Web_Resource_Parent="1" Rank="2"/>
    <WEB_RESOURCE DTYPE="PageImpl" Id_Web_Resource="4" Label="NULL" Url="http://www.mock-url4.org/" Id_Web_Resource_Parent="1" Rank="3"/>
    
</dataset>

=== Tanaguru/Tanaguru/engine/persistence/src/test/resources/dataSets/processRemarkFlatXmlDataSet.xml
<!DOCTYPE dataset SYSTEM "src/test/resources/dataSets/test.dtd">
<dataset>
    
    <REFERENCE Id_Reference="1" Cd_Reference="01" Description="" Label="Ref 1.0" Rank="1" Url="http://www.mock-ref1.org/"/>
    <REFERENCE Id_Reference="2" Cd_Reference="02" Description="" Label="Ref 2.0" Rank="2" Url="http://www.mock-ref2.org/"/>

    <THEME Id_Theme="1" Cd_Theme="01" Label="Theme1" Rank="1"/>
    <THEME Id_Theme="2" Cd_Theme="02" Label="Theme2" Rank="2"/>
    <THEME Id_Theme="3" Cd_Theme="03" Label="Theme3" Rank="3"/>

    <CRITERION Id_Criterion="1" Reference_Id_Reference="1" Theme_Id_Theme="1" Cd_Criterion="0101" Description="Critere 1.1" Label="1.1" Url="http://www.mock-criterion1.1.org/" Rank="1"/>
    <CRITERION Id_Criterion="2" Reference_Id_Reference="1" Theme_Id_Theme="2" Cd_Criterion="0102" Description="Critere 1.2" Label="1.2" Url="http://www.mock-criterion1.2.org/" Rank="2"/>
    <CRITERION Id_Criterion="3" Reference_Id_Reference="2" Theme_Id_Theme="3" Cd_Criterion="0103" Description="Critere 1.3" Label="1.3" Url="http://www.mock-criterion1.3.org/" Rank="3"/>
    <CRITERION Id_Criterion="4" Reference_Id_Reference="2" Theme_Id_Theme="3" Cd_Criterion="0104" Description="Critere 1.4" Label="1.4" Url="http://www.mock-criterion1.4.org/" Rank="4"/>

    <SCOPE Id_Scope="1" Code="page" Description="page" Label="Page" />
    <SCOPE Id_Scope="2" Code="site" Description="site" Label="Site" />
    
    <LEVEL Id_Level="1" Cd_Level="Bz" Description="Level1" Label="Level1" Rank="1"/>
    <LEVEL Id_Level="2" Cd_Level="Ar" Description="Level2" Label="Level2" Rank="2"/>
    <LEVEL Id_Level="3" Cd_Level="Or" Description="Level3" Label="Level3" Rank="3"/>

    <TEST Id_Test="1" Cd_Test="10101" Description="Test 1.1.1" Label="1.1.1" Rank="1" Weight="1.0" Id_Criterion="1" Id_Scope="2" Id_Level="1" No_Process="false"/>
    <TEST Id_Test="2" Cd_Test="10102" Description="Test 1.1.2" Label="1.1.2" Rank="2" Weight="1.0" Id_Criterion="2" Id_Scope="1" Id_Level="1" No_Process="false"/>
    <TEST Id_Test="3" Cd_Test="10103" Description="Test 1.1.3" Label="1.1.3" Rank="3" Weight="1.0" Id_Criterion="1" Id_Scope="2" Id_Level="1" No_Process="false"/>
    <TEST Id_Test="4" Cd_Test="10104" Description="Test 1.1.4" Label="1.1.4" Rank="4" Weight="1.0" Id_Criterion="2" Id_Scope="1" Id_Level="1" No_Process="false"/>
    <TEST Id_Test="5" Cd_Test="10105" Description="Test 1.1.5" Label="1.1.5" Rank="5" Weight="1.0" Id_Criterion="1" Id_Scope="1" Id_Level="1" No_Process="false"/>
    <TEST Id_Test="6" Cd_Test="10106" Description="Test 1.1.6" Label="1.1.6" Rank="6" Weight="1.0" Id_Criterion="2" Id_Scope="1" Id_Level="1" No_Process="false"/>
    <TEST Id_Test="7" Cd_Test="10107" Description="Test 1.1.7" Label="1.1.7" Rank="7" Weight="1.0" Id_Criterion="2" Id_Scope="1" Id_Level="2" No_Process="false"/>
    <TEST Id_Test="8" Cd_Test="10108" Description="Test 1.1.8" Label="1.1.8" Rank="8" Weight="1.0" Id_Criterion="1" Id_Scope="1" Id_Level="2" No_Process="false"/>
    <TEST Id_Test="9" Cd_Test="10109" Description="Test 1.1.9" Label="1.1.9" Rank="9" Weight="1.0" Id_Criterion="2" Id_Scope="1" Id_Level="2" No_Process="false"/>
    <TEST Id_Test="10" Cd_Test="10110" Description="Test 1.1.10" Label="1.1.10" Rank="10" Weight="1.0" Id_Criterion="2" Id_Scope="1" Id_Level="1" No_Process="false"/>
    <TEST Id_Test="11" Cd_Test="10111" Description="Test 1.1.11" Label="1.1.11" Rank="11" Weight="1.0" Id_Criterion="3" Id_Scope="1" Id_Level="1" No_Process="false"/>
    <TEST Id_Test="12" Cd_Test="10112" Description="Test 1.1.12" Label="1.1.12" Rank="12" Weight="1.0" Id_Criterion="3" Id_Scope="1" Id_Level="1" No_Process="false"/>
    <TEST Id_Test="13" Cd_Test="10113" Description="Test 1.1.13" Label="1.1.13" Rank="13" Weight="1.0" Id_Criterion="3" Id_Scope="1" Id_Level="1" No_Process="false"/>
    <TEST Id_Test="14" Cd_Test="10114" Description="Test 1.1.14" Label="1.1.14" Rank="14" Weight="1.0" Id_Criterion="4" Id_Scope="1" Id_Level="2" No_Process="false"/>
    <TEST Id_Test="15" Cd_Test="10115" Description="Test 1.1.15" Label="1.1.15" Rank="15" Weight="1.0" Id_Criterion="4" Id_Scope="1" Id_Level="2" No_Process="false"/>

    <AUDIT Id_Audit="1" Dt_Creation="2010-10-26 13:50:29" Status="COMPLETED"/>
    <AUDIT Id_Audit="2" Dt_Creation="2010-10-26 14:50:29" Status="COMPLETED"/>
    
    <WEB_RESOURCE DTYPE="PageImpl" Id_Web_Resource="1" Label="NULL" Url="http://www.mock-url.org/1.html" Id_Audit="1" Rank="1"/>
    <WEB_RESOURCE DTYPE="PageImpl" Id_Web_Resource="2" Label="NULL" Url="http://www.mock-url.org/2.html" Id_Audit="2" Rank="1" />

    <PROCESS_RESULT DTYPE="DefiniteResultImpl" Id_Process_Result="1" Definite_Value="NEED_MORE_INFO" Element_Counter="2" Id_Web_Resource="1" Id_Test="1" Id_Audit_Net_Result="1" Id_Audit_Gross_Result="1"/>
    <PROCESS_RESULT DTYPE="DefiniteResultImpl" Id_Process_Result="2" Definite_Value="PASSED" Element_Counter="2" Id_Web_Resource="1" Id_Test="2" Id_Audit_Net_Result="1" Id_Audit_Gross_Result="1"/>
    <PROCESS_RESULT DTYPE="IndefiniteResultImpl" Id_Process_Result="3" Indefinite_Value="EMPTY" Element_Counter="2" Id_Web_Resource="1" Id_Test="3" Id_Audit_Net_Result="1" Id_Audit_Gross_Result="1"/>
    <PROCESS_RESULT DTYPE="DefiniteResultImpl" Id_Process_Result="4" Definite_Value="NEED_MORE_INFO" Element_Counter="2" Id_Web_Resource="1" Id_Test="4" Id_Audit_Net_Result="1" Id_Audit_Gross_Result="1"/>
    <PROCESS_RESULT DTYPE="DefiniteResultImpl" Id_Process_Result="5" Definite_Value="PASSED" Element_Counter="2" Id_Web_Resource="1" Id_Test="5" Id_Audit_Net_Result="1" Id_Audit_Gross_Result="1"/>
    <PROCESS_RESULT DTYPE="IndefiniteResultImpl" Id_Process_Result="6" Indefinite_Value="EMPTY" Element_Counter="2" Id_Web_Resource="1" Id_Test="6" Id_Audit_Net_Result="1" Id_Audit_Gross_Result="1"/>
    <PROCESS_RESULT DTYPE="DefiniteResultImpl" Id_Process_Result="7" Definite_Value="NEED_MORE_INFO" Element_Counter="2" Id_Web_Resource="2" Id_Test="1" Id_Audit_Net_Result="2" Id_Audit_Gross_Result="2"/>
    <PROCESS_RESULT DTYPE="DefiniteResultImpl" Id_Process_Result="8" Definite_Value="FAILED" Element_Counter="2" Id_Web_Resource="1" Id_Test="7" Id_Audit_Net_Result="1" Id_Audit_Gross_Result="1"/>
    <PROCESS_RESULT DTYPE="IndefiniteResultImpl" Id_Process_Result="9" Indefinite_Value="EMPTY" Element_Counter="2" Id_Web_Resource="1" Id_Test="8" Id_Audit_Net_Result="1" Id_Audit_Gross_Result="1"/>
    <PROCESS_RESULT DTYPE="DefiniteResultImpl" Id_Process_Result="10" Definite_Value="FAILED" Element_Counter="2" Id_Web_Resource="1" Id_Test="9" Id_Audit_Net_Result="1" Id_Audit_Gross_Result="1"/>
    <PROCESS_RESULT DTYPE="DefiniteResultImpl" Id_Process_Result="11" Definite_Value="NOT_APPLICABLE" Element_Counter="2" Id_Web_Resource="2" Id_Test="2" Id_Audit_Net_Result="2" Id_Audit_Gross_Result="2"/>
    <PROCESS_RESULT DTYPE="IndefiniteResultImpl" Id_Process_Result="12" Indefinite_Value="EMPTY" Element_Counter="2" Id_Web_Resource="1" Id_Test="10" Id_Audit_Net_Result="1" Id_Audit_Gross_Result="1"/>

</dataset>
